Name: Product
Host: 0.0.0.0
Port: 8081

Mysql:
  DataSource: root:123456@tcp(localhost:3306)/go-zero-shop?charset=utf8mb4&parseTime=true
CacheRedis:
  - Host: redis:6380
    Type: node
    Pass:
Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400
ProductRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: product.rpc